name: zombie-dice-pucpr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    run: cypress run -s cypress/Google.feature
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./ --file Dockerfile -t lucasmelniski/zombie-dice-pucpr:latest

  deploy:
    run: docker push lucasmelniski/zombie-dice-pucpr:latest
